<?php
session_start();
require_once "config/database.php";

if(!isset($_SESSION["loggedin"]) || $_SESSION["loggedin"] !== true){
    header("location: login.php");
    exit;
}

$user_id = $_SESSION["id"];

// Get all completed reports
$sql = "SELECT * FROM reports WHERE user_id = ? AND status = 'completed' ORDER BY generated_at DESC";
$stmt = $mysqli->prepare($sql);
$stmt->bind_param("i", $user_id);
$stmt->execute();
$result = $stmt->get_result();

// Generate filename
$filename = "all_reports_" . date('Y-m-d') . ".xls";

// Set headers for Excel download
header("Content-Type: application/vnd.ms-excel");
header("Content-Disposition: attachment; filename=\"$filename\"");
header("Cache-Control: max-age=0");

// Start output
echo "<html>";
echo "<head>";
echo "<style>
    table { border-collapse: collapse; width: 100%; }
    th { background-color: #2c3e50; color: white; padding: 10px; border: 1px solid #ddd; }
    td { padding: 8px; border: 1px solid #ddd; }
    .report-section { margin-bottom: 30px; }
    .header { text-align: center; font-size: 20px; font-weight: bold; margin-bottom: 20px; color: #2c3e50; }
</style>";
echo "</head>";
echo "<body>";

echo "<div class='header'>All Electrical Monitoring Reports</div>";
echo "<p><strong>User:</strong> " . $_SESSION['username'] . "</p>";
echo "<p><strong>Export Date:</strong> " . date('Y-m-d H:i:s') . "</p>";
echo "<p><strong>Total Reports:</strong> " . $result->num_rows . "</p>";
echo "<hr>";

if($result->num_rows > 0){
    $report_count = 1;
    while($report = $result->fetch_assoc()){
        echo "<div class='report-section'>";
        echo "<h3>Report #" . $report_count . ": " . htmlspecialchars($report['report_name']) . "</h3>";
        
        echo "<table border='1'>";
        echo "<tr><th>Field</th><th>Value</th></tr>";
        echo "<tr><td>Report ID</td><td>#" . $report['id'] . "</td></tr>";
        echo "<tr><td>Report Type</td><td>" . ucfirst($report['report_type']) . "</td></tr>";
        echo "<tr><td>Date Range</td><td>" . $report['start_date'] . " to " . $report['end_date'] . "</td></tr>";
        echo "<tr><td>Generated On</td><td>" . date('Y-m-d H:i:s', strtotime($report['generated_at'])) . "</td></tr>";
        echo "<tr><td>Status</td><td>" . ucfirst($report['status']) . "</td></tr>";
        
        // Try to decode and show some summary data
        $report_data = json_decode($report['parameters'], true);
        if($report_data && isset($report_data['summary'])){
            $summary = $report_data['summary'];
            echo "<tr><td colspan='2' style='background-color: #f8f9fa;'><strong>Summary Statistics</strong></td></tr>";
            echo "<tr><td>Total Records</td><td>" . ($summary['total_records'] ?? 0) . "</td></tr>";
            echo "<tr><td>Avg Voltage</td><td>" . round(($summary['avg_voltage'] ?? 0), 2) . " V</td></tr>";
            echo "<tr><td>Avg Current</td><td>" . round(($summary['avg_current'] ?? 0), 2) . " A</td></tr>";
            echo "<tr><td>Avg Power</td><td>" . round(($summary['avg_power'] ?? 0), 2) . " W</td></tr>";
            echo "<tr><td>Total Energy</td><td>" . round(($summary['total_power'] ?? 0) / 1000, 2) . " kWh</td></tr>";
        }
        
        echo "</table>";
        echo "</div>";
        echo "<hr>";
        
        $report_count++;
    }
} else {
    echo "<p>No reports found for export.</p>";
}

echo "<p style='font-size: 12px; color: #666;'>Generated by Electrical Monitoring System</p>";
echo "</body>";
echo "</html>";

// Log the export activity
$log_sql = "INSERT INTO activity_logs (user_id, action, details) VALUES (?, 'export_all_reports', ?)";
$log_stmt = $mysqli->prepare($log_sql);
$details = "Exported all reports";
$log_stmt->bind_param("is", $user_id, $details);
$log_stmt->execute();
$log_stmt->close();

$stmt->close();
$mysqli->close();
exit;
?>